export const GET_CURRENT_USER_START = 'GET_CURRENT_USER_START';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';

export const EDIT_CURRENT_USER_START = 'EDIT_CURRENT_USER_START';
export const EDIT_CURRENT_USER_SUCCESS = 'EDIT_CURRENT_USER_SUCCESS';
export const EDIT_CURRENT_USER_ERROR = 'EDIT_CURRENT_USER_ERROR';

export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const EDIT_PASSWORD_START = 'GET_USERS_START';
export const EDIT_PASSWORD_SUCCESS = 'GET_USERS_SUCCESS';
export const EDIT_PASSWORD_ERROR = 'GET_USERS_ERROR';

export const UPLOAD_AVATAR_START = 'UPLOAD_AVATAR_START';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_ERROR = 'UPLOAD_AVATAR_ERROR';
